### PR TITLE
Short Task 1 Completed

### PR DESCRIPTION
**Pull request by Reene-Simon**
### Short Description of what this resolves:
- Created a doc file and wrote my thoughts about the various components and their need on the mentioned websites in the issue description 

### Changes proposed in this pull request and/or Screenshots of changes:
- Created a txt file with my GitHub username and added it to the Task 1 folder.
- Added the relevant doc link to this text file.

### CODE REVIEW

**Comment by Reene-Simon** [comment]
@D-Hacker26 could u please tell me why the PR has been closed? I have written about 3 components. The issue has requested for only 2.

**Comment by D-Hacker26** [comment]
@Reene-Simon if you have gone through the readme properly you would have found the images of three websites....the issue asked you to explain the UX features for all three of them plus if you had any suggestions for the UX design you could also add that....

**Comment by D-Hacker26** [comment]
@Reene-Simon you had to suggest " 2 features for each page ".....pls read the readmes very carefully

**Comment by Reene-Simon** [comment]
@D-Hacker26 it's written in the MDC "Atleast suggest two features of the pages". It isn't mentioned for each page.

**Comment by D-Hacker26** [comment]
@Reene-Simon page"s"!

**Comment by Reene-Simon** [comment]
@D-Hacker26 Yes it's written pages but not specified that we hv to do for each page is what I'm saying. Honestly I did see some of the other PR's and most have written only 1 feature for each page and yet it's merged. I'll make the changes requested but do accept the PR as I've written it all on my own and taken effort for the same. Also, a request is that plz do write the reason the PR is closed so that we can understand what has gone wrong. It was very unfortunate that within 5 mins of my PR being closed the issue too was closed. Hence, I request that the PR be considered.

**Comment by D-Hacker26** [comment]
@Reene-Simon the issue is closed now...the point system backend  wont work now for a closed issue....as it was the first task i have been lenient in judging but all the PRs that have been merged contains features for all the 3 websites mentioned in the README....also there are a 100 PR so sometimes it is not practically possible to comment on every closed PR due to shortage of time though I try my best to tell the required changes

**Pull request closed without merging**
