### PR TITLE
Create Mansi.txt

### PR DESCRIPTION
**Pull request by Mannxxx**
Isssue: #315

### CODE REVIEW

**Comment by D-Hacker26** [comment]
@Mannxxx why are you using direct images of a design and placing them instead of designing it on figma?.....I have been telling you the same thing again and again but still the mistake is taking place in each and every PR you make....Its the last warning from my side any further usage of direct images would result in banning you from the repo.

**Comment by Mannxxx** [comment]
> @Mannxxx why are you using direct images of a design and placing them instead of designing it on figma?.....I have been telling you the same thing again and again but still the mistake is taking place in each and every PR you make....Its the last warning from my side any further usage of direct images would result in banning you from the repo.

Okay Sorry, I'll remove them and make a new pull request.

**Comment by Mannxxx** [comment]
https://www.figma.com/file/HRzN48HvntcMAS5jjH5ORN/Untitled?type=design&node-id=0%3A1&mode=design&t=DfQWJYu6wAknoaQW-1

Could you check if its fine now? I'll make a pull request once you approve.

**Comment by D-Hacker26** [comment]
@Mannxxx added comments in the figma file

**Pull request closed without merging**
